import { Metadata  } from "next";
import './styles/globals.css';
import Image from "next/image";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next-js Tutorial",
    template: "%s | Ayobami"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="flex font-sans text-2xl not-italic font-bold " 
         style={{ //backgroundColor:
           //"light-gray",
          padding: "1rem",}}>
          <h2><Image src="/spend-guard.jpg" width={50} height={50} alt="logo"></Image>Spend Guard</h2>
        </header>
        {children}
        <footer className=" bg-slate-950"
          style={{
           color:"whitesmoke" ,
            // backgroundColor: "#000080",
            padding: "1rem",
            // margin: "0px 185px 0px 185px",
            justifyItems: "center",
            display:"grid",
            justifySelf:"center"
          }}>
          <h2 className="flex"><Image src="/spend-guard.jpg" width={50} height={50} alt=""></Image>Spend Guard</h2>
          <h2>Contact us</h2> 
           <p>Email: basskeydayo@gmail.com</p>
            <p>NET-ZERO</p>
            
            <p>&copy; 2024 Spend Guard. All rights reserved.
          </p>
          <p>Privacy Terms</p>
          
        </footer>
        </body>
    </html>
  )
}
